version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sleep", "infinity"]
    ports:
      - "8080:90"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: psql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=golang_with_docker_model_1_db
      - POSTGRES_USER=taguilera
      - POSTGRES_PASSWORD=tomaguilera1995
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
